//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection_point
    {
        public collection_point()
        {
            this.department_detail = new HashSet<department_detail>();
        }
    
        public int collection_point_id { get; set; }
        public string collection_point_name { get; set; }
    
        public virtual ICollection<department_detail> department_detail { get; set; }
    }
}
