//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_order_detail
    {
        public int delivery_order_detail_id { get; set; }
        public int delivery_order_qty { get; set; }
        public int delivery_order_delivery_order_id { get; set; }
        public string item_item_id { get; set; }
    
        public virtual delivery_order delivery_order { get; set; }
        public virtual item item { get; set; }
    }
}
