//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_detail
    {
        public int department_detail_id { get; set; }
        public int collection_point_collection_point_id { get; set; }
        public int department_department_id { get; set; }
        public int employee_hod { get; set; }
        public int employee_rep { get; set; }
    
        public virtual collection_point collection_point { get; set; }
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
