//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.department_detail = new HashSet<department_detail>();
            this.department_detail1 = new HashSet<department_detail>();
            this.employee_delegation = new HashSet<employee_delegation>();
            this.employee_delegation1 = new HashSet<employee_delegation>();
            this.outstandings = new HashSet<outstanding>();
            this.purchase_order = new HashSet<purchase_order>();
            this.purchase_order1 = new HashSet<purchase_order>();
            this.requisitions = new HashSet<requisition>();
        }
    
        public int employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_type { get; set; }
        public int employee_number { get; set; }
        public string employee_gender { get; set; }
        public string employee_email { get; set; }
        public int employee_phone { get; set; }
        public string employee_password { get; set; }
        public int department_department_id { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<department_detail> department_detail { get; set; }
        public virtual ICollection<department_detail> department_detail1 { get; set; }
        public virtual ICollection<employee_delegation> employee_delegation { get; set; }
        public virtual ICollection<employee_delegation> employee_delegation1 { get; set; }
        public virtual ICollection<outstanding> outstandings { get; set; }
        public virtual ICollection<purchase_order> purchase_order { get; set; }
        public virtual ICollection<purchase_order> purchase_order1 { get; set; }
        public virtual ICollection<requisition> requisitions { get; set; }
    }
}
