//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.delivery_order_detail = new HashSet<delivery_order_detail>();
            this.disbursement_list = new HashSet<disbursement_list>();
            this.item_supplier_list = new HashSet<item_supplier_list>();
            this.outstandings = new HashSet<outstanding>();
            this.purchase_order_detail = new HashSet<purchase_order_detail>();
            this.requisition_detail = new HashSet<requisition_detail>();
            this.stock_adjustment = new HashSet<stock_adjustment>();
            this.stockcards = new HashSet<stockcard>();
        }
    
        public string item_id { get; set; }
        public string item_description { get; set; }
        public int item_reorder_level { get; set; }
        public int item_reorder_qty { get; set; }
        public int category_category_id { get; set; }
        public int uom_uom_id { get; set; }
        public int item_virtual_balance { get; set; }
        public string item_status { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<delivery_order_detail> delivery_order_detail { get; set; }
        public virtual ICollection<disbursement_list> disbursement_list { get; set; }
        public virtual ICollection<item_supplier_list> item_supplier_list { get; set; }
        public virtual uom uom { get; set; }
        public virtual ICollection<outstanding> outstandings { get; set; }
        public virtual ICollection<purchase_order_detail> purchase_order_detail { get; set; }
        public virtual ICollection<requisition_detail> requisition_detail { get; set; }
        public virtual ICollection<stock_adjustment> stock_adjustment { get; set; }
        public virtual ICollection<stockcard> stockcards { get; set; }
    }
}
