//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_supplier_list
    {
        public int item_supplier_list_id { get; set; }
        public int item_supplier_list_price { get; set; }
        public string item_item_id { get; set; }
        public string supplier_supplier_id { get; set; }
    
        public virtual item item { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
