//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LUEntities : DbContext
    {
        public LUEntities()
            : base("name=LUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> categories { get; set; }
        public DbSet<collection_point> collection_point { get; set; }
        public DbSet<delivery_order> delivery_order { get; set; }
        public DbSet<delivery_order_detail> delivery_order_detail { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<department_detail> department_detail { get; set; }
        public DbSet<disbursement_list> disbursement_list { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<employee_delegation> employee_delegation { get; set; }
        public DbSet<item> items { get; set; }
        public DbSet<item_supplier_list> item_supplier_list { get; set; }
        public DbSet<outstanding> outstandings { get; set; }
        public DbSet<purchase_order> purchase_order { get; set; }
        public DbSet<purchase_order_detail> purchase_order_detail { get; set; }
        public DbSet<requisition> requisitions { get; set; }
        public DbSet<requisition_detail> requisition_detail { get; set; }
        public DbSet<stock_adjustment> stock_adjustment { get; set; }
        public DbSet<stockcard> stockcards { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<uom> uoms { get; set; }
    }
}
