//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class outstanding
    {
        public int outstanding_id { get; set; }
        public int outstanding_remaining_qty { get; set; }
        public System.DateTime outstanding_created_date { get; set; }
        public System.DateTime outstanding_processed_date { get; set; }
        public string item_item_id { get; set; }
        public int employee_employee_id { get; set; }
        public string requisition_requisition_id { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual item item { get; set; }
        public virtual requisition requisition { get; set; }
    }
}
