//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase_order
    {
        public purchase_order()
        {
            this.delivery_order = new HashSet<delivery_order>();
            this.purchase_order_detail = new HashSet<purchase_order_detail>();
        }
    
        public int purchase_order_id { get; set; }
        public int purchase_order_number { get; set; }
        public System.DateTime purchase_order_date { get; set; }
        public int purchase_order_status { get; set; }
        public string supplier_supplier_id { get; set; }
        public int purchase_order_ordered_by { get; set; }
        public int purchase_order_approved_by { get; set; }
    
        public virtual ICollection<delivery_order> delivery_order { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual ICollection<purchase_order_detail> purchase_order_detail { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
