//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_adjustment
    {
        public int stock_adjustment_id { get; set; }
        public string stock_adjustment_voucher_id { get; set; }
        public string stock_adjustment_qty { get; set; }
        public int stock_adjustment_price { get; set; }
        public string stock_adjustment_status { get; set; }
        public string stock_adjustment_reason { get; set; }
        public System.DateTime stock_adjustment_date { get; set; }
        public string item_item_id { get; set; }
    
        public virtual item item { get; set; }
    }
}
