//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockcard
    {
        public int stockcard_id { get; set; }
        public System.DateTime stockcard_date { get; set; }
        public string stockcard_qty { get; set; }
        public int stockcard_balance { get; set; }
        public string item_item_id { get; set; }
    
        public virtual item item { get; set; }
    }
}
