//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForm_V1.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.item_supplier_list = new HashSet<item_supplier_list>();
            this.purchase_order = new HashSet<purchase_order>();
        }
    
        public string supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_contact_name { get; set; }
        public int supplier_phone { get; set; }
        public int supplier_fax { get; set; }
        public string supplier_address { get; set; }
        public string supplier_gst_registration_number { get; set; }
    
        public virtual ICollection<item_supplier_list> item_supplier_list { get; set; }
        public virtual ICollection<purchase_order> purchase_order { get; set; }
    }
}
